name: social_downloader
description: "Social downloader app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  provider: ^6.1.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.1
  gallery_saver: ^2.3.2
  flutter_svg:
  awesome_snackbar_content: ^0.1.3
  internet_connection_checker: ^1.0.0+1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.1.0
  open_file: ^3.3.2
  open_file_manager: ^1.0.2
  image_picker: ^1.1.2
  android_intent_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
